# Generated by Django 5.0.2 on 2024-02-17 16:18

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='video_files')),
                ('height', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20)])),
                ('is_processing', models.BooleanField(blank=True, default=None, null=True)),
                ('processing_success', models.BooleanField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
