# Generated by Django 5.0.2 on 2024-02-17 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='width',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20)]),
        ),
    ]
